"""
Eduvia — Activity Generation Schemas (Phase 4)

Defines strict Pydantic schemas for all activity types generated by the
Activity Generation Engine.

Supported Activity Types:
1. matching: Connecting paired items across categories.
2. multiple_choice: Selecting target item among options with calibrated distractors.
3. ordering: Arranging sequence items in continuum.
4. visual_identification: Identifying items/regions within an accessible visual scene.
5. drag_drop: Categorizing items into target zones.

All schemas enforce pedagogical clarity, cognitive calm, and complete determinism.
"""
from __future__ import annotations

import uuid
from enum import StrEnum
from typing import Annotated, Any, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


class ActivityType(StrEnum):
    """Supported activity modalities for Eduvia."""
    MATCHING = "matching"
    MULTIPLE_CHOICE = "multiple_choice"
    ORDERING = "ordering"
    VISUAL_IDENTIFICATION = "visual_identification"
    DRAG_DROP = "drag_drop"


# ── Modality 1: Multiple Choice ──────────────────────────────────────────────


class MultipleChoiceOption(BaseModel):
    """Single selectable option in a multiple choice activity."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Unique identifier for the option (e.g., 'opt_1')")
    text: str = Field(..., min_length=1, description="Text displayed to the learner")
    visual_cue: str | None = Field(default=None, description="Optional icon or visual representation")
    is_correct: bool = Field(default=False, description="Whether this option is the correct answer")
    distractor_rationale: str | None = Field(
        default=None,
        description="Teacher/system rationale for why this distractor is pedagogically informative",
    )


class MultipleChoiceContent(BaseModel):
    """Payload for multiple choice activities."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.MULTIPLE_CHOICE] = ActivityType.MULTIPLE_CHOICE
    question: str = Field(..., min_length=3, description="The primary prompt or question for the learner")
    options: list[MultipleChoiceOption] = Field(
        ..., min_length=2, max_length=5, description="Selectable options (2-5 options to prevent cognitive overload)"
    )
    correct_answer_id: str = Field(default="", description="ID of the correct option")
    explanation: str = Field(
        default="", description="Calm, encouraging explanation revealed after response"
    )


# ── Modality 2: Matching ─────────────────────────────────────────────────────


class MatchingItem(BaseModel):
    """Item on one side of a matching activity."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Unique item identifier (e.g., 'left_1')")
    label: str = Field(..., min_length=1, description="Visible text or symbol")
    visual_cue: str | None = Field(default=None, description="Visual symbol or icon key")


class MatchingPair(BaseModel):
    """Defines a correct match between a left item and a right item."""
    model_config = ConfigDict(frozen=True)

    left_id: str = Field(..., description="ID from left_items")
    right_id: str = Field(..., description="ID from right_items")


class MatchingContent(BaseModel):
    """Payload for matching pairs activity."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.MATCHING] = ActivityType.MATCHING
    prompt: str = Field(..., min_length=3, description="Instructions (e.g., 'Match the numeral to the count')")
    left_items: list[MatchingItem] = Field(
        ..., min_length=2, max_length=5, description="Items displayed on the left"
    )
    right_items: list[MatchingItem] = Field(
        ..., min_length=2, max_length=5, description="Items displayed on the right"
    )
    pairs: list[MatchingPair] = Field(default_factory=list, description="Correct left-right pairs")


# ── Modality 3: Ordering ─────────────────────────────────────────────────────


class OrderingItem(BaseModel):
    """Item to be ordered along a sequence."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Unique identifier (e.g., 'seq_1')")
    label: str = Field(..., min_length=1, description="Text or number")
    visual_cue: str | None = Field(default=None, description="Optional supporting visual")


class OrderingContent(BaseModel):
    """Payload for sequence or continuum ordering activity."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.ORDERING] = ActivityType.ORDERING
    prompt: str = Field(..., min_length=3, description="Instructions (e.g., 'Put the numbers in order from smallest to largest')")
    items: list[OrderingItem] = Field(
        ..., min_length=3, max_length=6, description="Items to arrange (3-6 items)"
    )
    correct_sequence: list[str] = Field(
        default_factory=list, description="List of item IDs in the correct order"
    )
    direction: str = Field(
        default="ascending",
        description="Continuum direction: 'ascending', 'descending', or 'chronological'",
    )


# ── Modality 4: Visual Identification ────────────────────────────────────────


class VisualElement(BaseModel):
    """An identifiable element within a visual scene."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Element identifier")
    label: str = Field(..., min_length=1, description="Name or descriptive label")
    category: str = Field(default="general", description="Category of element")
    is_target: bool = Field(default=False, description="Whether this is the element the learner should identify")
    bounding_hint: str | None = Field(
        default=None,
        description="Position hint in the scene (e.g., 'top-left', 'center', 'on the table')",
    )


class VisualIdentificationContent(BaseModel):
    """Payload for finding/identifying an object in a visual scenario."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.VISUAL_IDENTIFICATION] = ActivityType.VISUAL_IDENTIFICATION
    prompt: str = Field(..., min_length=3, description="Instructions (e.g., 'Find all the red circles')")
    scene_description: str = Field(
        ..., min_length=5, description="Accessible textual description of the visual scene"
    )
    elements: list[VisualElement] = Field(
        ..., min_length=2, max_length=6, description="Elements present in the scene"
    )
    target_id: str = Field(default="", description="ID of the target element")
    feedback_clue: str = Field(
        default="", description="Gentle hint guiding learner attention toward the target"
    )


# ── Modality 5: Drag & Drop ──────────────────────────────────────────────────


class DragItem(BaseModel):
    """Item that can be dragged into a drop zone."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Unique draggable item ID")
    label: str = Field(..., min_length=1, description="Text or symbol on the item")
    visual_cue: str | None = Field(default=None, description="Optional icon/color cue")


class DropZone(BaseModel):
    """Target category or bucket for drop items."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Drop zone identifier")
    label: str = Field(..., min_length=1, description="Bucket title (e.g., 'Even Numbers', 'Odd Numbers')")
    capacity: int = Field(default=5, ge=1, le=10, description="Max items allowed in zone")


class DragDropContent(BaseModel):
    """Payload for sorting/categorizing items into zones."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.DRAG_DROP] = ActivityType.DRAG_DROP
    prompt: str = Field(..., min_length=3, description="Instructions (e.g., 'Sort the shapes by color')")
    items: list[DragItem] = Field(
        ..., min_length=2, max_length=6, description="Items to sort"
    )
    zones: list[DropZone] = Field(
        ..., min_length=2, max_length=4, description="Target buckets/zones"
    )
    correct_mapping: dict[str, str] = Field(
        default_factory=dict, description="Map of drag item ID -> target zone ID"
    )


# ── Discriminated Union for Activity Content ─────────────────────────────────

ActivityContent = Annotated[
    Union[
        MultipleChoiceContent,
        MatchingContent,
        OrderingContent,
        VisualIdentificationContent,
        DragDropContent,
    ],
    Field(discriminator="activity_type"),
]


# ── Question Entity & Canonical Activity Container ───────────────────────────


class ActivityQuestion(BaseModel):
    """
    Discrete interactive question item within an Activity container.
    Wraps the modality-specific interaction payload without duplicating prompt fields.
    """
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Stable unique identifier for this question")
    question_number: int = Field(..., ge=1, description="1-indexed sequence order within the activity")
    question_type: ActivityType = Field(..., description="Modality of this specific question")
    content: ActivityContent = Field(..., description="Modality-specific interactive payload (options, pairs, zones, etc.)")
    content_source_key: str | None = Field(default=None, description="Authoritative ContentBank provenance key")
    hints: list[str] = Field(default_factory=list, description="Scaffolding hints specific to this question")
    explanation: str | None = Field(default=None, description="Pedagogical explanation revealed post-evaluation")
    weight: float = Field(default=1.0, ge=0.1, le=5.0, description="Relative score weight")


class Activity(BaseModel):
    """
    Standardized Activity representation conforming to Eduvia's Phase 4 specification.
    
    Guarantees deterministic, validated output for frontend rendering,
    whether generated via Gemini or constructed by deterministic fallback.
    Supports both multi-question containers (default) and single-question legacy consumers.
    """
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID = Field(default_factory=uuid.uuid4, description="Unique activity instance ID")
    objective_id: uuid.UUID | str = Field(..., description="Associated learning objective ID or slug")
    activity_type: ActivityType = Field(..., description="Primary modality of this activity")
    title: str = Field(..., min_length=1, description="Short, friendly title")
    instructions: str = Field(..., min_length=1, description="Clear, sensory-appropriate directions")
    difficulty_level: int = Field(default=1, ge=1, le=5, description="Difficulty level 1-5")
    questions: list[ActivityQuestion] = Field(default_factory=list, description="Ordered question items in this activity")
    content: ActivityContent | None = Field(
        default=None,
        description="Deprecated: for single-question legacy consumers. Mirrors questions[0].content.",
    )
    hints: list[str] = Field(
        default_factory=list,
        description="Faded scaffolding hints (level 1 subtle, level 2 guided, level 3 explicit)",
    )
    scaffolding_level: int = Field(default=1, ge=1, le=3, description="Current scaffolding assistance tier")
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Generation metadata (e.g. provider, model, latency, fallback_used)",
    )

    @model_validator(mode="before")
    @classmethod
    def synchronize_questions_and_content(cls, data: Any) -> Any:
        if isinstance(data, dict):
            questions = data.get("questions")
            content = data.get("content")
            act_type = data.get("activity_type")
            if (not questions or len(questions) == 0) and content is not None:
                # Wrap legacy single content into a question
                q_type = act_type
                if isinstance(content, dict):
                    q_type = content.get("activity_type")
                elif hasattr(content, "activity_type"):
                    q_type = getattr(content, "activity_type", None)
                if not q_type:
                    q_type = ActivityType.MULTIPLE_CHOICE
                data["questions"] = [
                    {
                        "id": "q_1",
                        "question_number": 1,
                        "question_type": q_type,
                        "content": content,
                        "content_source_key": data.get("metadata", {}).get("content_source_key") if isinstance(data.get("metadata"), dict) else None,
                        "hints": data.get("hints") or [],
                        "explanation": content.get("explanation") if isinstance(content, dict) else getattr(content, "explanation", None),
                        "weight": 1.0,
                    }
                ]
            elif questions and len(questions) > 0 and content is None:
                first_q = questions[0]
                data["content"] = first_q.get("content") if isinstance(first_q, dict) else getattr(first_q, "content", None)
        return data

    @model_validator(mode="after")
    def validate_homogeneous_modalities(self) -> Activity:
        for q in self.questions:
            if q.question_type != self.activity_type:
                raise ValueError(
                    f"Question {q.id} modality '{q.question_type.value}' does not match activity modality '{self.activity_type.value}'"
                )
        return self

    def to_learner_safe(self) -> LearnerActivity:
        """Produce a learner-safe representation with all answer keys completely stripped."""
        safe_questions: list[LearnerActivityQuestion] = []
        for q in self.questions:
            safe_content = _sanitize_content_to_learner_safe(q.content)
            safe_questions.append(
                LearnerActivityQuestion(
                    id=q.id,
                    question_number=q.question_number,
                    question_type=q.question_type,
                    content=safe_content,
                    hints=list(q.hints or []),
                    weight=q.weight,
                )
            )

        top_safe_content = (
            safe_questions[0].content
            if safe_questions
            else (_sanitize_content_to_learner_safe(self.content) if self.content else None)
        )

        return LearnerActivity(
            id=self.id,
            objective_id=self.objective_id,
            activity_type=self.activity_type,
            title=self.title,
            instructions=self.instructions,
            difficulty_level=self.difficulty_level,
            questions=safe_questions,
            content=top_safe_content,
            hints=list(self.hints or []),
            scaffolding_level=self.scaffolding_level,
            metadata={
                k: v for k, v in (self.metadata or {}).items()
                if not k.startswith("internal_") and k not in ("correct_answer", "answer_key")
            },
        )


# ── Learner-Safe Response Schemas (Zero Answer-Truth Exposure) ───────────────


class LearnerMultipleChoiceOption(BaseModel):
    """Learner-facing selectable option (no answer key or distractor rationale)."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Unique identifier for the option (e.g., 'opt_1')")
    text: str = Field(..., min_length=1, description="Text displayed to the learner")
    visual_cue: str | None = Field(default=None, description="Optional icon or visual representation")


class LearnerMultipleChoiceContent(BaseModel):
    """Learner-facing multiple choice payload (no correct_answer_id, no explanation)."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.MULTIPLE_CHOICE] = ActivityType.MULTIPLE_CHOICE
    question: str = Field(..., min_length=3, description="The primary prompt or question for the learner")
    options: list[LearnerMultipleChoiceOption] = Field(
        ..., min_length=2, max_length=5, description="Selectable options"
    )


class LearnerMatchingContent(BaseModel):
    """Learner-facing matching payload (no authoritative pairs mapping)."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.MATCHING] = ActivityType.MATCHING
    prompt: str = Field(..., min_length=3, description="Instructions")
    left_items: list[MatchingItem] = Field(..., min_length=2, max_length=5)
    right_items: list[MatchingItem] = Field(..., min_length=2, max_length=5)


class LearnerOrderingContent(BaseModel):
    """Learner-facing ordering payload (no correct_sequence)."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.ORDERING] = ActivityType.ORDERING
    prompt: str = Field(..., min_length=3, description="Instructions")
    items: list[OrderingItem] = Field(..., min_length=3, max_length=6)
    direction: str = Field(default="ascending")


class LearnerVisualElement(BaseModel):
    """Learner-facing scene element (no is_target indicator)."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Element identifier")
    label: str = Field(..., min_length=1, description="Name or descriptive label")
    category: str = Field(default="general", description="Category of element")
    bounding_hint: str | None = Field(default=None)


class LearnerVisualIdentificationContent(BaseModel):
    """Learner-facing visual scene payload (no target_id, no feedback_clue)."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.VISUAL_IDENTIFICATION] = ActivityType.VISUAL_IDENTIFICATION
    prompt: str = Field(..., min_length=3)
    scene_description: str = Field(..., min_length=5)
    elements: list[LearnerVisualElement] = Field(..., min_length=2, max_length=6)


class LearnerDragDropContent(BaseModel):
    """Learner-facing drag & drop payload (no correct_mapping)."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.DRAG_DROP] = ActivityType.DRAG_DROP
    prompt: str = Field(..., min_length=3)
    items: list[DragItem] = Field(..., min_length=2, max_length=6)
    zones: list[DropZone] = Field(..., min_length=2, max_length=4)


LearnerActivityContent = Annotated[
    Union[
        LearnerMultipleChoiceContent,
        LearnerMatchingContent,
        LearnerOrderingContent,
        LearnerVisualIdentificationContent,
        LearnerDragDropContent,
    ],
    Field(discriminator="activity_type"),
]


class LearnerActivityQuestion(BaseModel):
    """Learner-facing question container with no authoritative answers or explanations."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Stable unique identifier for this question")
    question_number: int = Field(..., ge=1)
    question_type: ActivityType = Field(..., description="Modality of this specific question")
    content: LearnerActivityContent = Field(..., description="Learner-safe interactive content")
    hints: list[str] = Field(default_factory=list)
    weight: float = Field(default=1.0, ge=0.1, le=5.0)


class LearnerActivity(BaseModel):
    """Learner-facing activity model completely sanitized of answer keys."""
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID = Field(default_factory=uuid.uuid4, description="Unique activity instance ID")
    objective_id: uuid.UUID | str = Field(..., description="Associated learning objective ID or slug")
    activity_type: ActivityType = Field(..., description="Primary modality of this activity")
    title: str = Field(..., min_length=1)
    instructions: str = Field(..., min_length=1)
    difficulty_level: int = Field(default=1, ge=1, le=5)
    questions: list[LearnerActivityQuestion] = Field(default_factory=list)
    content: LearnerActivityContent | None = Field(default=None)
    hints: list[str] = Field(default_factory=list)
    scaffolding_level: int = Field(default=1, ge=1, le=3)
    metadata: dict[str, Any] = Field(default_factory=dict)


def _sanitize_content_to_learner_safe(content: ActivityContent | Any) -> LearnerActivityContent:
    if isinstance(content, MultipleChoiceContent):
        return LearnerMultipleChoiceContent(
            activity_type=ActivityType.MULTIPLE_CHOICE,
            question=content.question,
            options=[
                LearnerMultipleChoiceOption(
                    id=opt.id,
                    text=opt.text,
                    visual_cue=opt.visual_cue,
                )
                for opt in content.options
            ],
        )
    elif isinstance(content, MatchingContent):
        return LearnerMatchingContent(
            activity_type=ActivityType.MATCHING,
            prompt=content.prompt,
            left_items=content.left_items,
            right_items=content.right_items,
        )
    elif isinstance(content, OrderingContent):
        return LearnerOrderingContent(
            activity_type=ActivityType.ORDERING,
            prompt=content.prompt,
            items=content.items,
            direction=content.direction,
        )
    elif isinstance(content, VisualIdentificationContent):
        return LearnerVisualIdentificationContent(
            activity_type=ActivityType.VISUAL_IDENTIFICATION,
            prompt=content.prompt,
            scene_description=content.scene_description,
            elements=[
                LearnerVisualElement(
                    id=elem.id,
                    label=elem.label,
                    category=elem.category,
                    bounding_hint=elem.bounding_hint,
                )
                for elem in content.elements
            ],
        )
    elif isinstance(content, DragDropContent):
        return LearnerDragDropContent(
            activity_type=ActivityType.DRAG_DROP,
            prompt=content.prompt,
            items=content.items,
            zones=content.zones,
        )
    elif isinstance(
        content,
        (
            LearnerMultipleChoiceContent,
            LearnerMatchingContent,
            LearnerOrderingContent,
            LearnerVisualIdentificationContent,
            LearnerDragDropContent,
        ),
    ):
        return content
    elif isinstance(content, dict):
        act_type = content.get("activity_type")
        if act_type == ActivityType.MULTIPLE_CHOICE:
            return LearnerMultipleChoiceContent(
                activity_type=ActivityType.MULTIPLE_CHOICE,
                question=content.get("question", ""),
                options=[
                    LearnerMultipleChoiceOption(
                        id=opt.get("id", ""),
                        text=opt.get("text", ""),
                        visual_cue=opt.get("visual_cue"),
                    ) if isinstance(opt, dict) else opt
                    for opt in content.get("options", [])
                ],
            )
        elif act_type == ActivityType.MATCHING:
            return LearnerMatchingContent(
                activity_type=ActivityType.MATCHING,
                prompt=content.get("prompt", ""),
                left_items=content.get("left_items", []),
                right_items=content.get("right_items", []),
            )
        elif act_type == ActivityType.ORDERING:
            return LearnerOrderingContent(
                activity_type=ActivityType.ORDERING,
                prompt=content.get("prompt", ""),
                items=content.get("items", []),
                direction=content.get("direction", "left_to_right"),
            )
        elif act_type == ActivityType.VISUAL_IDENTIFICATION:
            return LearnerVisualIdentificationContent(
                activity_type=ActivityType.VISUAL_IDENTIFICATION,
                prompt=content.get("prompt", ""),
                scene_description=content.get("scene_description", ""),
                elements=[
                    LearnerVisualElement(
                        id=elem.get("id", ""),
                        label=elem.get("label", ""),
                        category=elem.get("category", "general"),
                        bounding_hint=elem.get("bounding_hint"),
                    ) if isinstance(elem, dict) else elem
                    for elem in content.get("elements", [])
                ],
            )
        elif act_type == ActivityType.DRAG_DROP:
            return LearnerDragDropContent(
                activity_type=ActivityType.DRAG_DROP,
                prompt=content.get("prompt", ""),
                items=content.get("items", []),
                zones=content.get("zones", []),
            )
    raise ValueError(f"Unsupported content type for learner sanitization: {type(content)}")


# ── Request / Response DTOs ──────────────────────────────────────────────────


class ActivityGenerateRequest(BaseModel):
    """Request payload to generate an activity (GenerationSpec)."""
    objective_id: uuid.UUID | str = Field(..., description="Target learning objective UUID or identifier")
    learner_id: uuid.UUID | None = Field(
        default=None,
        description="Optional learner UUID to contextualize generation using profile evidence",
    )
    subject_id: uuid.UUID | str | None = Field(default=None, description="Optional subject UUID/key")
    unit_id: uuid.UUID | str | None = Field(default=None, description="Optional unit UUID/key")
    lesson_id: uuid.UUID | str | None = Field(default=None, description="Optional lesson UUID/key")
    activity_type: ActivityType | None = Field(
        default=None,
        description="Optional explicit activity type override. If None, chosen from profile or objective defaults.",
    )

    @field_validator("activity_type", mode="before")
    @classmethod
    def normalize_activity_type(cls, v: Any) -> Any:
        if v in ("auto", "", None):
            return None
        return v
    difficulty_level: int | None = Field(
        default=None,
        ge=1,
        le=5,
        description="Optional explicit difficulty tier (1-5). If None, respects teacher overrides or objective difficulty.",
    )
    question_count: int = Field(
        default=5,
        ge=3,
        le=10,
        description="Target number of distinct questions in the activity (3-10, default 5)",
    )
    item_count: int = Field(
        default=4,
        ge=2,
        le=10,
        description="Target number of interactive items, choices, or matching pairs per question (2-10)",
    )
    language: str = Field(
        default="en",
        description="Language code for generation ('en', 'ar', etc.)",
    )
    visual_style: str = Field(
        default="calm",
        description="Visual presentation style ('calm', 'simple', 'high_contrast', 'playful')",
    )
    scaffolding_level: int = Field(
        default=1,
        ge=0,
        le=3,
        description="Scaffolding tier (0=none/independent, 1=gentle hints, 2=guided support, 3=explicit modeling)",
    )
    interaction_style: str = Field(
        default="direct",
        description="Interaction modality style ('direct', 'guided', 'exploratory')",
    )
    teacher_instructions: str | None = Field(
        default=None,
        description="Custom teacher instructions for framing, real-world examples, or specific classroom constraints",
    )
    mode: Literal["activity", "lesson"] = Field(
        default="activity",
        description="Generation mode: 'activity' for single interactive task, 'lesson' for 10-minute structured mini-lesson",
    )
    seed: int | None = Field(
        default=None,
        description="Optional seed / variation index for reproducible variation during regeneration",
    )
    phase8_locked_difficulty: int | None = Field(
        default=None,
        ge=1,
        le=5,
        description="Authoritative adaptive engine locked difficulty that overrides teacher selection when active",
    )


# Alias for explicit domain clarity
GenerationSpec = ActivityGenerateRequest


class EffectiveGenerationPrompt(BaseModel):
    """Structured representation of the compiled generation prompt for transparency and safety."""
    system_prompt: str = Field(..., description="System instructions and immutable safety rules")
    user_prompt: str = Field(..., description="User prompt incorporating curriculum, learner, and teacher parameters")
    full_prompt_text: str = Field(..., description="Complete readable preview combining all sections")
    sections: dict[str, str] = Field(..., description="Dictionary mapping section names to text bodies")
    teacher_editable_section: str = Field(..., description="Isolated teacher instructions text")
    immutable_sections: list[str] = Field(..., description="List of system-controlled immutable section titles")
    grounding_sources: list[dict[str, Any]] = Field(default_factory=list, description="RAG retrieved knowledge passages")
    content_bank_grounded: bool = Field(default=False, description="Whether authoritative Content Bank facts ground this prompt")
    objective_title: str = Field(default="", description="Target objective title")
    activity_type: str = Field(default="", description="Target activity type")
    difficulty_level: int = Field(default=1, description="Effective difficulty level")


class ActivityGenerateResponse(BaseModel):
    """Response returned when an activity has been generated and validated."""
    activity: LearnerActivity | Activity
    fallback_used: bool = Field(
        ..., description="True if deterministic fallback was triggered due to LLM failure/timeout/validation error"
    )
    generation_source: str = Field(
        ..., description="Source of generation ('gemini', 'mock', 'deterministic_fallback')"
    )
    learner_id: uuid.UUID | None = Field(default=None)
    objective_id: uuid.UUID | str
    grounding_sources: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Verified knowledge sources retrieved via RAG for pedagogical grounding",
    )


class LessonPlan(BaseModel):
    """Structured, validated mini-lesson plan generated by GenAI or ContentBank fallback."""
    id: uuid.UUID = Field(default_factory=uuid.uuid4)
    objective_id: uuid.UUID | str
    title: str = Field(..., min_length=3, description="Lesson title")
    objective: str = Field(..., min_length=5, description="Lesson learning objective")
    duration_minutes: int = Field(default=10, ge=5, le=45, description="Planned lesson duration in minutes")
    introduction: str = Field(..., description="Warm-up / hook connecting to prior knowledge")
    demonstration: str = Field(..., description="Teacher modeling / 'I Do' phase demonstrating the key concept")
    guided_practice: str = Field(..., description="'We Do' phase with collaborative prompts and scaffolded checks")
    independent_practice: str = Field(..., description="'You Do' phase outlining learner practice expectation")
    scaffolding: str = Field(..., description="Tiered support, accommodations, and gentle cues")
    teacher_notes: str = Field(..., description="Pedagogical observations and common misconceptions to watch for")
    recap: str = Field(..., description="Closure / exit check summarizing foundational mastery")
    suggested_activity_type: ActivityType = Field(default=ActivityType.MULTIPLE_CHOICE)
    activity: Activity | None = Field(default=None, description="Embedded practice activity instance")
    generation_source: str = Field(default="gemini")
    fallback_used: bool = Field(default=False)
    grounding_sources: list[dict[str, Any]] = Field(default_factory=list)


class LessonGenerateResponse(BaseModel):
    """Response returned when a mini-lesson has been generated and validated."""
    lesson_plan: LessonPlan
    fallback_used: bool
    generation_source: str
    objective_id: uuid.UUID | str
    grounding_sources: list[dict[str, Any]] = Field(default_factory=list)


class ActivityUpdateRequest(BaseModel):
    """Payload for safe teacher edits to an existing activity."""
    title: str | None = Field(default=None, min_length=2, description="Updated activity title")
    instructions: str | None = Field(default=None, min_length=3, description="Updated instructions wording")
    hints: list[str] | None = Field(default=None, description="Updated graded hints")
    teacher_notes: str | None = Field(default=None, description="Teacher notes or observations")


class ActivityGenerationSummary(BaseModel):
    """Summary item for session activity library."""
    id: uuid.UUID
    objective_id: uuid.UUID | str
    activity_type: ActivityType
    difficulty_level: int
    title: str
    generation_source: str
    fallback_used: bool
    created_at: str
    grounding_sources_count: int = 0


# ── Phase 5: Learner Submission Payloads ──────────────────────────────────────


class MultipleChoiceSubmission(BaseModel):
    """Learner submission payload for Multiple Choice."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.MULTIPLE_CHOICE] = ActivityType.MULTIPLE_CHOICE
    selected_option_id: str = Field(..., min_length=1, description="ID of the option chosen by the learner")


class MatchingSubmission(BaseModel):
    """Learner submission payload for Matching."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.MATCHING] = ActivityType.MATCHING
    pairs: list[MatchingPair] = Field(
        ..., description="List of left-to-right pairs connected by the learner"
    )


class OrderingSubmission(BaseModel):
    """Learner submission payload for Ordering."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.ORDERING] = ActivityType.ORDERING
    ordered_ids: list[str] = Field(
        ..., min_length=1, description="Sequence of item IDs as arranged by the learner"
    )


class VisualIdentificationSubmission(BaseModel):
    """Learner submission payload for Visual Identification."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.VISUAL_IDENTIFICATION] = ActivityType.VISUAL_IDENTIFICATION
    selected_element_id: str = Field(
        ..., min_length=1, description="ID of the identified target element in the visual scene"
    )


class DragDropSubmission(BaseModel):
    """Learner submission payload for Drag and Drop."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.DRAG_DROP] = ActivityType.DRAG_DROP
    item_to_zone_mapping: dict[str, str] = Field(
        ..., description="Map of draggable item ID -> assigned drop zone ID"
    )


ActivitySubmissionPayload = Annotated[
    Union[
        MultipleChoiceSubmission,
        MatchingSubmission,
        OrderingSubmission,
        VisualIdentificationSubmission,
        DragDropSubmission,
    ],
    Field(discriminator="activity_type"),
]


# ── Phase 5: Interaction & Evaluation DTOs ────────────────────────────────────


class QuestionSubmission(BaseModel):
    """Learner submission for an individual question item."""
    model_config = ConfigDict(frozen=True)

    question_id: str = Field(..., description="Stable question identifier (e.g. 'q_1')")
    submission: ActivitySubmissionPayload = Field(..., description="Modality-specific answer payload")
    hints_used: int = Field(default=0, ge=0, le=10, description="Hints viewed for this specific question")
    time_spent_seconds: float = Field(default=0.0, ge=0.0, description="Time spent on this question in seconds")


class ActivitySubmissionRequest(BaseModel):
    """Request sent when a learner submits an answer for evaluation."""
    activity_id: uuid.UUID = Field(..., description="ID of the activity being answered")
    objective_id: uuid.UUID | str = Field(..., description="ID of the associated learning objective")
    activity_type: ActivityType = Field(..., description="Modality of the activity")
    questions: list[QuestionSubmission] = Field(
        default_factory=list,
        description="List of per-question answers submitted by the learner",
    )
    submission: ActivitySubmissionPayload | None = Field(
        default=None,
        description="Legacy single-question submission payload (for backward compatibility)",
    )
    learner_id: uuid.UUID | None = Field(
        default=None, description="Optional learner ID for session tracking"
    )
    hints_used: int = Field(
        default=0, ge=0, le=50, description="Total count of scaffolding hints viewed during the activity"
    )
    time_spent_seconds: float = Field(
        default=0.0, ge=0.0, description="Total seconds spent on this activity interaction"
    )
    activity_content: ActivityContent | None = Field(
        default=None,
        description="Authoritative activity content for stateless evaluation or cached sessions",
    )

    @model_validator(mode="before")
    @classmethod
    def normalize_legacy_submission(cls, data: Any) -> Any:
        if isinstance(data, dict):
            questions = data.get("questions")
            sub = data.get("submission")
            if not questions and sub is None:
                raise ValueError("Either 'questions' or 'submission' payload must be provided.")
            if (not questions or len(questions) == 0) and sub is not None:
                data["questions"] = [
                    {
                        "question_id": "q_1",
                        "submission": sub,
                        "hints_used": data.get("hints_used", 0),
                        "time_spent_seconds": data.get("time_spent_seconds", 0.0),
                    }
                ]
            elif questions and len(questions) > 0 and sub is None:
                first_q = questions[0]
                data["submission"] = first_q.get("submission") if isinstance(first_q, dict) else getattr(first_q, "submission", None)
        return data


class QuestionEvaluationResult(BaseModel):
    """Authoritative evaluation result for a single question item."""
    question_id: str = Field(..., description="Evaluated question ID")
    question_number: int = Field(default=1, ge=1)
    is_correct: bool = Field(..., description="Whether the response is completely correct")
    score: float = Field(..., ge=0.0, le=1.0, description="Question score (0.0 to 1.0 with partial credit)")
    feedback: str = Field(..., description="Positive, clear, non-shaming feedback for this question")
    explanation: str | None = Field(default=None, description="Pedagogical explanation revealed post-response")
    correct_answer_summary: dict[str, Any] = Field(default_factory=dict)
    evaluation_details: dict[str, Any] = Field(default_factory=dict)
    hints_used: int = Field(default=0)
    time_spent_seconds: float = Field(default=0.0)


class ActivityEvaluationResponse(BaseModel):
    """Authoritative evaluation result generated strictly by backend logic."""
    activity_id: uuid.UUID = Field(..., description="Evaluated activity ID")
    is_correct: bool = Field(..., description="Whether the response is completely correct")
    score: float = Field(
        ..., ge=0.0, le=1.0, description="Calculated accuracy score between 0.0 and 1.0"
    )
    questions_total: int = Field(default=1, ge=1, description="Total number of questions in activity")
    questions_answered: int = Field(default=1, ge=0, description="Number of questions answered by learner")
    questions_correct: int = Field(default=0, ge=0, description="Number of fully correct questions")
    percentage: float = Field(default=0.0, ge=0.0, le=100.0, description="Overall percentage (0.0 to 100.0)")
    mastery_achieved: bool = Field(
        ..., description="Whether accuracy and assistance satisfy objective criteria"
    )
    feedback: str = Field(
        ..., description="Cognitive Calm feedback designed to be clear, positive, and non-shaming"
    )
    question_results: list[QuestionEvaluationResult] = Field(
        default_factory=list,
        description="Detailed evaluation results for every question item in the activity",
    )
    explanation: str | None = Field(
        default=None, description="Pedagogical explanation or guidance for post-interaction learning"
    )
    correct_answer_summary: dict[str, Any] = Field(
        default_factory=dict, description="Authoritative correct answer summary"
    )
    hints_used: int = Field(default=0, description="Number of hints learner consulted")
    assistance_level: int = Field(
        default=0, ge=0, le=3, description="Assistance tier (0=independent, 1=subtle, 2=guided, 3=explicit)"
    )
    evaluation_details: dict[str, Any] = Field(
        default_factory=dict, description="Detailed diagnostic breakdown of the submission"
    )


class ActivityInteractionState(BaseModel):
    """Represents the in-progress or completed interaction state of an activity."""
    session_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    activity_id: uuid.UUID
    objective_id: uuid.UUID | str
    activity_type: ActivityType
    learner_id: uuid.UUID | None = None
    started_at: str = Field(..., description="ISO 8601 start timestamp")
    completed_at: str | None = Field(default=None, description="ISO 8601 completion timestamp")
    hints_used: int = Field(default=0)
    time_spent_seconds: float = Field(default=0.0)
    is_completed: bool = Field(default=False)
    submission: ActivitySubmissionPayload | None = None
    evaluation: ActivityEvaluationResponse | None = None

