"""
Eduvia — Activity Generation Schemas (Phase 4)

Defines strict Pydantic schemas for all activity types generated by the
Activity Generation Engine.

Supported Activity Types:
1. matching: Connecting paired items across categories.
2. multiple_choice: Selecting target item among options with calibrated distractors.
3. ordering: Arranging sequence items in continuum.
4. visual_identification: Identifying items/regions within an accessible visual scene.
5. drag_drop: Categorizing items into target zones.

All schemas enforce pedagogical clarity, cognitive calm, and complete determinism.
"""
from __future__ import annotations

import uuid
from enum import StrEnum
from typing import Annotated, Any, Literal, Union

from pydantic import BaseModel, ConfigDict, Field


class ActivityType(StrEnum):
    """Supported activity modalities for Eduvia."""
    MATCHING = "matching"
    MULTIPLE_CHOICE = "multiple_choice"
    ORDERING = "ordering"
    VISUAL_IDENTIFICATION = "visual_identification"
    DRAG_DROP = "drag_drop"


# ── Modality 1: Multiple Choice ──────────────────────────────────────────────


class MultipleChoiceOption(BaseModel):
    """Single selectable option in a multiple choice activity."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Unique identifier for the option (e.g., 'opt_1')")
    text: str = Field(..., min_length=1, description="Text displayed to the learner")
    visual_cue: str | None = Field(default=None, description="Optional icon or visual representation")
    is_correct: bool = Field(..., description="Whether this option is the correct answer")
    distractor_rationale: str | None = Field(
        default=None,
        description="Teacher/system rationale for why this distractor is pedagogically informative",
    )


class MultipleChoiceContent(BaseModel):
    """Payload for multiple choice activities."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.MULTIPLE_CHOICE] = ActivityType.MULTIPLE_CHOICE
    question: str = Field(..., min_length=3, description="The primary prompt or question for the learner")
    options: list[MultipleChoiceOption] = Field(
        ..., min_length=2, max_length=5, description="Selectable options (2-5 options to prevent cognitive overload)"
    )
    correct_answer_id: str = Field(..., description="ID of the correct option")
    explanation: str = Field(
        ..., min_length=1, description="Calm, encouraging explanation revealed after response"
    )


# ── Modality 2: Matching ─────────────────────────────────────────────────────


class MatchingItem(BaseModel):
    """Item on one side of a matching activity."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Unique item identifier (e.g., 'left_1')")
    label: str = Field(..., min_length=1, description="Visible text or symbol")
    visual_cue: str | None = Field(default=None, description="Visual symbol or icon key")


class MatchingPair(BaseModel):
    """Defines a correct match between a left item and a right item."""
    model_config = ConfigDict(frozen=True)

    left_id: str = Field(..., description="ID from left_items")
    right_id: str = Field(..., description="ID from right_items")


class MatchingContent(BaseModel):
    """Payload for matching pairs activity."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.MATCHING] = ActivityType.MATCHING
    prompt: str = Field(..., min_length=3, description="Instructions (e.g., 'Match the numeral to the count')")
    left_items: list[MatchingItem] = Field(
        ..., min_length=2, max_length=5, description="Items displayed on the left"
    )
    right_items: list[MatchingItem] = Field(
        ..., min_length=2, max_length=5, description="Items displayed on the right"
    )
    pairs: list[MatchingPair] = Field(..., min_length=2, max_length=5, description="Correct left-right pairs")


# ── Modality 3: Ordering ─────────────────────────────────────────────────────


class OrderingItem(BaseModel):
    """Item to be ordered along a sequence."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Unique identifier (e.g., 'seq_1')")
    label: str = Field(..., min_length=1, description="Text or number")
    visual_cue: str | None = Field(default=None, description="Optional supporting visual")


class OrderingContent(BaseModel):
    """Payload for sequence or continuum ordering activity."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.ORDERING] = ActivityType.ORDERING
    prompt: str = Field(..., min_length=3, description="Instructions (e.g., 'Put the numbers in order from smallest to largest')")
    items: list[OrderingItem] = Field(
        ..., min_length=3, max_length=6, description="Items to arrange (3-6 items)"
    )
    correct_sequence: list[str] = Field(
        ..., min_length=3, max_length=6, description="List of item IDs in the correct order"
    )
    direction: str = Field(
        default="ascending",
        description="Continuum direction: 'ascending', 'descending', or 'chronological'",
    )


# ── Modality 4: Visual Identification ────────────────────────────────────────


class VisualElement(BaseModel):
    """An identifiable element within a visual scene."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Element identifier")
    label: str = Field(..., min_length=1, description="Name or descriptive label")
    category: str = Field(default="general", description="Category of element")
    is_target: bool = Field(..., description="Whether this is the element the learner should identify")
    bounding_hint: str | None = Field(
        default=None,
        description="Position hint in the scene (e.g., 'top-left', 'center', 'on the table')",
    )


class VisualIdentificationContent(BaseModel):
    """Payload for finding/identifying an object in a visual scenario."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.VISUAL_IDENTIFICATION] = ActivityType.VISUAL_IDENTIFICATION
    prompt: str = Field(..., min_length=3, description="Instructions (e.g., 'Find all the red circles')")
    scene_description: str = Field(
        ..., min_length=5, description="Accessible textual description of the visual scene"
    )
    elements: list[VisualElement] = Field(
        ..., min_length=2, max_length=6, description="Elements present in the scene"
    )
    target_id: str = Field(..., description="ID of the target element")
    feedback_clue: str = Field(
        ..., min_length=1, description="Gentle hint guiding learner attention toward the target"
    )


# ── Modality 5: Drag & Drop ──────────────────────────────────────────────────


class DragItem(BaseModel):
    """Item that can be dragged into a drop zone."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Unique draggable item ID")
    label: str = Field(..., min_length=1, description="Text or symbol on the item")
    visual_cue: str | None = Field(default=None, description="Optional icon/color cue")


class DropZone(BaseModel):
    """Target category or bucket for drop items."""
    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Drop zone identifier")
    label: str = Field(..., min_length=1, description="Bucket title (e.g., 'Even Numbers', 'Odd Numbers')")
    capacity: int = Field(default=5, ge=1, le=10, description="Max items allowed in zone")


class DragDropContent(BaseModel):
    """Payload for sorting/categorizing items into zones."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.DRAG_DROP] = ActivityType.DRAG_DROP
    prompt: str = Field(..., min_length=3, description="Instructions (e.g., 'Sort the shapes by color')")
    items: list[DragItem] = Field(
        ..., min_length=2, max_length=6, description="Items to sort"
    )
    zones: list[DropZone] = Field(
        ..., min_length=2, max_length=4, description="Target buckets/zones"
    )
    correct_mapping: dict[str, str] = Field(
        ..., description="Map of drag item ID -> target zone ID"
    )


# ── Discriminated Union for Activity Content ─────────────────────────────────

ActivityContent = Annotated[
    Union[
        MultipleChoiceContent,
        MatchingContent,
        OrderingContent,
        VisualIdentificationContent,
        DragDropContent,
    ],
    Field(discriminator="activity_type"),
]


# ── Canonical Activity Entity ────────────────────────────────────────────────


class Activity(BaseModel):
    """
    Standardized Activity representation conforming to Eduvia's Phase 4 specification.
    
    Guarantees deterministic, validated output for frontend rendering,
    whether generated via Gemini or constructed by deterministic fallback.
    """
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID = Field(default_factory=uuid.uuid4, description="Unique activity instance ID")
    objective_id: uuid.UUID = Field(..., description="Associated learning objective ID")
    activity_type: ActivityType = Field(..., description="Modality of this activity")
    title: str = Field(..., min_length=1, description="Short, friendly title")
    instructions: str = Field(..., min_length=1, description="Clear, sensory-appropriate directions")
    difficulty_level: int = Field(default=1, ge=1, le=5, description="Difficulty level 1-5")
    content: ActivityContent = Field(..., description="Type-specific structured activity payload")
    hints: list[str] = Field(
        default_factory=list,
        description="Faded scaffolding hints (level 1 subtle, level 2 guided, level 3 explicit)",
    )
    scaffolding_level: int = Field(default=1, ge=1, le=3, description="Current scaffolding assistance tier")
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Generation metadata (e.g. provider, model, latency, fallback_used)",
    )


# ── Request / Response DTOs ──────────────────────────────────────────────────


class ActivityGenerateRequest(BaseModel):
    """Request payload to generate an activity."""
    objective_id: uuid.UUID = Field(..., description="Target learning objective UUID")
    learner_id: uuid.UUID | None = Field(
        default=None,
        description="Optional learner UUID to contextualize generation using profile evidence",
    )
    activity_type: ActivityType | None = Field(
        default=None,
        description="Optional explicit activity type override. If None, chosen from profile or objective defaults.",
    )
    difficulty_level: int | None = Field(
        default=None,
        ge=1,
        le=5,
        description="Optional explicit difficulty tier. If None, respects teacher overrides or objective difficulty.",
    )
    language: str = Field(
        default="en",
        description="Language code for generation ('en', 'ar', etc.)",
    )


class ActivityGenerateResponse(BaseModel):
    """Response returned when an activity has been generated and validated."""
    activity: Activity
    fallback_used: bool = Field(
        ..., description="True if deterministic fallback was triggered due to LLM failure/timeout/validation error"
    )
    generation_source: str = Field(
        ..., description="Source of generation ('gemini', 'mock', 'deterministic_fallback')"
    )
    learner_id: uuid.UUID | None = Field(default=None)
    objective_id: uuid.UUID


# ── Phase 5: Learner Submission Payloads ──────────────────────────────────────


class MultipleChoiceSubmission(BaseModel):
    """Learner submission payload for Multiple Choice."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.MULTIPLE_CHOICE] = ActivityType.MULTIPLE_CHOICE
    selected_option_id: str = Field(..., min_length=1, description="ID of the option chosen by the learner")


class MatchingSubmission(BaseModel):
    """Learner submission payload for Matching."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.MATCHING] = ActivityType.MATCHING
    pairs: list[MatchingPair] = Field(
        ..., description="List of left-to-right pairs connected by the learner"
    )


class OrderingSubmission(BaseModel):
    """Learner submission payload for Ordering."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.ORDERING] = ActivityType.ORDERING
    ordered_ids: list[str] = Field(
        ..., min_length=1, description="Sequence of item IDs as arranged by the learner"
    )


class VisualIdentificationSubmission(BaseModel):
    """Learner submission payload for Visual Identification."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.VISUAL_IDENTIFICATION] = ActivityType.VISUAL_IDENTIFICATION
    selected_element_id: str = Field(
        ..., min_length=1, description="ID of the identified target element in the visual scene"
    )


class DragDropSubmission(BaseModel):
    """Learner submission payload for Drag and Drop."""
    model_config = ConfigDict(frozen=True)

    activity_type: Literal[ActivityType.DRAG_DROP] = ActivityType.DRAG_DROP
    item_to_zone_mapping: dict[str, str] = Field(
        ..., description="Map of draggable item ID -> assigned drop zone ID"
    )


ActivitySubmissionPayload = Annotated[
    Union[
        MultipleChoiceSubmission,
        MatchingSubmission,
        OrderingSubmission,
        VisualIdentificationSubmission,
        DragDropSubmission,
    ],
    Field(discriminator="activity_type"),
]


# ── Phase 5: Interaction & Evaluation DTOs ────────────────────────────────────


class ActivitySubmissionRequest(BaseModel):
    """Request sent when a learner submits an answer for evaluation."""
    activity_id: uuid.UUID = Field(..., description="ID of the activity being answered")
    objective_id: uuid.UUID = Field(..., description="ID of the associated learning objective")
    activity_type: ActivityType = Field(..., description="Modality of the activity")
    submission: ActivitySubmissionPayload = Field(
        ..., description="Modality-specific answer payload provided by learner"
    )
    learner_id: uuid.UUID | None = Field(
        default=None, description="Optional learner ID for session tracking"
    )
    hints_used: int = Field(
        default=0, ge=0, le=10, description="Count of scaffolding hints viewed during the activity"
    )
    time_spent_seconds: float = Field(
        default=0.0, ge=0.0, description="Total seconds spent on this interaction"
    )
    activity_content: ActivityContent | None = Field(
        default=None,
        description="Authoritative activity content for stateless evaluation or cached sessions",
    )


class ActivityEvaluationResponse(BaseModel):
    """Authoritative evaluation result generated strictly by backend logic."""
    activity_id: uuid.UUID = Field(..., description="Evaluated activity ID")
    is_correct: bool = Field(..., description="Whether the response is completely correct")
    score: float = Field(
        ..., ge=0.0, le=1.0, description="Calculated accuracy score between 0.0 and 1.0"
    )
    mastery_achieved: bool = Field(
        ..., description="Whether accuracy and assistance satisfy objective criteria"
    )
    feedback: str = Field(
        ..., description="Cognitive Calm feedback designed to be clear, positive, and non-shaming"
    )
    explanation: str | None = Field(
        default=None, description="Pedagogical explanation or guidance for post-interaction learning"
    )
    correct_answer_summary: dict[str, Any] = Field(
        default_factory=dict, description="Authoritative correct answer summary"
    )
    hints_used: int = Field(default=0, description="Number of hints learner consulted")
    assistance_level: int = Field(
        default=0, ge=0, le=3, description="Assistance tier (0=independent, 1=subtle, 2=guided, 3=explicit)"
    )
    evaluation_details: dict[str, Any] = Field(
        default_factory=dict, description="Detailed diagnostic breakdown of the submission"
    )


class ActivityInteractionState(BaseModel):
    """Represents the in-progress or completed interaction state of an activity."""
    session_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    activity_id: uuid.UUID
    objective_id: uuid.UUID
    activity_type: ActivityType
    learner_id: uuid.UUID | None = None
    started_at: str = Field(..., description="ISO 8601 start timestamp")
    completed_at: str | None = Field(default=None, description="ISO 8601 completion timestamp")
    hints_used: int = Field(default=0)
    time_spent_seconds: float = Field(default=0.0)
    is_completed: bool = Field(default=False)
    submission: ActivitySubmissionPayload | None = None
    evaluation: ActivityEvaluationResponse | None = None

